modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="afkfish"
version="${mod_version}"
displayName="AFKFish"
authors="Kyo"
description='''
Auto fish mod
'''

[[mixins]]
config="afkfish.mixins.json" # Load mixin từ common
[[mixins]]
config="afkfish.neoforge.mixins.json" # Load mixin riêng của NeoForge