modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="autofish"
version="${mod_version}"
displayName="autofish"
authors="Kyo"
description='''
Auto fish mod
'''

[[mixins]]
config="autofish.mixins.json" # Load mixin từ common
[[mixins]]
config="autofish.neoforge.mixins.json" # Load mixin riêng của NeoForge